import logging
from typing import Optional, Dict, Any

from src.core.memory import MemoryManager

logger = logging.getLogger(__name__)

class ExperienceBuffer:
    """
    Stores high-quality thought chains generated by System 2 (MCTS) into 
    long-term memory so that System 1 can retrieve them later as context.
    """
    
    def __init__(self, memory_manager: MemoryManager, min_reward_threshold: float = 0.8):
        """
        Args:
            memory_manager: The MemoryManager instance connected to ChromaDB.
            min_reward_threshold: Only experiences with a reward above this 
                                  are saved to long-term memory.
        """
        self.memory = memory_manager
        self.min_reward_threshold = min_reward_threshold

    def add_experience(self, query: str, thought_chain: str, reward: float, metadata: Optional[Dict[str, Any]] = None) -> bool:
        """
        Evaluates a completed reasoning chain and stores it if it meets the quality threshold.
        """
        if reward < self.min_reward_threshold:
            logger.debug(f"Experience rejected. Reward {reward} < threshold {self.min_reward_threshold}")
            return False
            
        experience_text = (
            f"=== PAST SUCCESSFUL REASONING ===\n"
            f"Query: {query}\n"
            f"Reasoning Steps:\n{thought_chain}\n"
            f"Final Reward Score: {reward:.2f}\n"
            f"================================="
        )
        
        meta = metadata or {}
        meta["type"] = "system2_experience"
        meta["reward"] = reward
        
        doc_id = self.memory.add_document(text=experience_text, metadata=meta)
        
        logger.info(f"High-quality experience saved to Memory. Reward: {reward:.2f}, DocID: {doc_id}")
        return True
